language: php

php:
  - 7.4
  - 8.0
  - 8.1

before_install:
  - echo "extension=ldap.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - bin/phpspec run --format=pretty --no-interaction
